# The URL the site will be built for
base_url = "https://reall0c.github.io/reall0c.github.io"
title = "reAll0c's cave den"
theme = "linkita"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# The default language. (type: string;)
default_language = "en"

# The default author for pages. See `extra.profiles`. (type: string;)
author = "reAll0c"

# The site description. (type: string;)
description = "The place where reAll0c's thoughts are stored."

# Automatically generate a feed. (type: boolean;)
generate_feeds = true

# The filenames to use for the feeds. (type: array of strings;)
feed_filenames = ["atom.xml"] # or ["rss.xml"]

# Build a search index from the pages and section content
#  for `default_language`. (type: boolean;)
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Enable KaTeX math formula support globally.
# (type: boolean; default value: `false`;)
math = false

# Enable Mermaid support globally.
# (type: boolean; default value: `false`;)
mermaid = false

# Enable comments globally.
# (type: boolean; default value: `false`;)
comment = false

# Title separator.
# (type: string; default value: ` | `;)
title_separator = " | "

# The top menu. See `extra.menus`.
# (type: string; no default value;)
header_menu_name = "menu_name"

# (type: boolean; default value: false;)
# disable_default_favicon = true

# (type: boolean; default value: false;)
# disable_javascript = true

# You can reorder the strings, remove them, or replace them.
#  For example, you can replace `site_title` with `home_button`.
#  (type: array of strings; default value: `["site_title", "theme_button", "search_button", "translations_button"]`;)
# header_buttons = []

# Valid values:
#  `date`, `date_on_page`, `date_on_paginator`,
#  `date_updated, `date_updated_on_page, `date_updated_on_paginator`,
#  `reading_time, `reading_time_on_page, `reading_time_on_paginator`,
#  `word_count`, `word_count_on_page`, `word_count_on_paginator`,
#  `authors`, `authors_on_page`, `authors_on_paginator`,
#  `tags`, `tags_on_page`, `tags_on_paginator`.
#  (type: array of strings; default value: `["date", "date_updated_on_page", "reading_time", "authors"]`;)
# page_info = []

[extra.style]
# The custom background color. (type: string;)
bg_color = "#f4f4f5"
# The custom background color in dark mode. (type: string;)
bg_dark_color = "#18181b"

# Enable header blur. (type: boolean;)
header_blur = false

# The custom header color, only available
#  when `header_blur` is false. (type: string;)
header_color = "#e4e4e7"
# The custom header color in dark mode, only available
#  when `header_blur` is false. (type: string;)
header_dark_color = "#27272a"

[extra.menus]
menu_name = [
  {url = "$BASE_URL/pages/archive/", name = "Archive"},
  {url = "$BASE_URL/categories", name = "Categories"},
  {url = "$BASE_URL/tags/", name = "Tags"},
  {url = "$BASE_URL/pages/about/", name = "About"},
]

# Replace `your_username` with your username.
[extra.profiles.your_username]
# The URL of avatar.
# (type: string; no default value;)
avatar_url = "icons/github.svg"

# A description of what is in the avatar.
# (type: string; no default value;)
avatar_alt = ""

# Invert avatar color in dark mode.
# (type: boolean; default value: `false`;)
avatar_invert = false

# Profile name for all languages.
# (type: string; default value: the username;)
name = "reAll0c"

# Profile bio for all languages.
# (type: string; supports markdown; no default value;)
bio = "A geek who loves to learn new things."

# Profile email.
# (type: string; no default value;)
# email = ""

# Profile website.
# (type: string; no default value;)
# url = ""

# Social icons.
# The `name` should be the file name of `static/icons/*.svg` or the icon name of https://simpleicons.org/
# The `url` supports `$BASE_URL`.
# (type: array of tables; no default value;)
social = [
    { name = "github", url = "https://github.com/reAll0c" },
    { name = "bluesky", url = "https://bsky.app/profile/reAll0c" },
    { name = "rss", url = "$BASE_URL/atom.xml" },
]

[extra.footer]
# Replace with the correct year.
# (type: number; default value: current year;)
since = 2025

# Replace with the url of the license you want.
# (type: string; no default value; supports `$BASE_URL`;)
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

# Replace `Your Name` with your name and `CC BY-SA 4.0` with the name of the license you want
copyright = "&copy; $YEAR Your Name &vert; [CC BY-SA 4.0]($LICENSE_URL)"

# (type: string; no default value; supports `$BASE_URL`;)
# privacy_policy_url = "$BASE_URL/privacy-policy/"

# (type: string; no default value; supports `$BASE_URL`;)
# terms_of_service_url = "$BASE_URL/terms-of-service/"

# (type: string; no default value; supports `$BASE_URL`;)
# search_page_url = "$BASE_URL/search/"